# Generated by Django 4.1.5 on 2023-01-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_course_question_quiz_quizsession_subject_teachers_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("question", "quiz_session")},
        ),
        migrations.AddConstraint(
            model_name="quizsession",
            constraint=models.CheckConstraint(
                check=models.Q(("started_at__lt", models.F("finished_at"))),
                name="started_at_finished_at_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizsession",
            constraint=models.CheckConstraint(
                check=models.Q(("started_at__lte", models.F("deadline"))),
                name="started_at_deadline_check",
            ),
        ),
    ]
