# Generated by Django 4.1.5 on 2023-01-28 14:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_subject_invitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="invitation_token",
            field=models.CharField(
                default=core.models.generate_invitation_token,
                max_length=50,
                unique=True,
            ),
        ),
    ]
