# Generated by Django 4.1.5 on 2023-01-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_useranswer_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "quizzes"},
        ),
        migrations.RemoveConstraint(
            model_name="quizsession",
            name="started_at_finished_at_check",
        ),
        migrations.RemoveConstraint(
            model_name="quizsession",
            name="started_at_deadline_check",
        ),
        migrations.AlterField(
            model_name="quizsession",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quizsession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="quizsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("started_at__isnull", True),
                        ("finished_at__isnull", True),
                        ("started_at__lt", models.F("finished_at")),
                        _connector="OR",
                    )
                ),
                name="started_at_finished_at_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("started_at__isnull", True),
                        ("started_at__lte", models.F("deadline")),
                        _connector="OR",
                    )
                ),
                name="started_at_deadline_check",
            ),
        ),
    ]
