# Generated by Django 4.1.5 on 2023-02-04 16:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_subject_invitation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="invitation_token",
            field=models.CharField(
                default=core.models.generate_invitation_token,
                max_length=50,
                unique=True,
            ),
        ),
    ]
