# Generated by Django 4.1.5 on 2023-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_course_invitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="value",
            field=models.PositiveIntegerField(),
        ),
    ]
